name: Log Artifact Workflow

on: [push]

jobs:
  log-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create log file
      run: |
        echo "Log entry 1: Workflow started" > test-log.txt
        echo "Log entry 2: Checking out repository" >> test-log.txt
        echo "Log entry 3: Creating log file" >> test-log.txt
        echo "Log entry 4: Uploading log file as artifact" >> test-log.txt
        echo "Log entry 5: Workflow completed" >> test-log.txt

    - name: Upload log file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-log
        path: test-log.txt

    # Testing section for GITHUB_TOKEN
    - name: Use GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "Using GITHUB_TOKEN for testing"

    # Testing section for ACTIONS_RUNTIME_TOKEN
    - name: Use ACTIONS_RUNTIME_TOKEN
      env:
        ACTIONS_RUNTIME_TOKEN: ${{ secrets.ACTIONS_RUNTIME_TOKEN }}
      run: echo "Using ACTIONS_RUNTIME_TOKEN for testing"

    # Download the artifact
    - name: Download log file artifact
      uses: actions/download-artifact@v4
      with:
        name: test-log
        path: .

    # New log entry for artifact content with environmental variables
    - name: Log artifact content
      run: |
        echo "Log entry 6: GITHUB_TOKEN is $GITHUB_TOKEN" >> test-log.txt
        echo "Log entry 7: ACTIONS_RUNTIME_TOKEN is $ACTIONS_RUNTIME_TOKEN" >> test-log.txt

    # Display updated log file contents
    - name: Display updated log file contents
      run: cat test-log.txt

    - name: Upload updated log file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: updated-test-log
        path: test-log.txt
