name: Log Artifact Workflow

on: [push]

jobs:
  log-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create log file
      run: |
        echo "Log entry 1: Workflow started" > test-log.txt
        echo "Log entry 2: Checking out repository" >> test-log.txt
        echo "Log entry 3: Creating log file" >> test-log.txt
        echo "Log entry 4: Uploading log file as artifact" >> test-log.txt
        echo "Log entry 5: Workflow completed" >> test-log.txt

    - name: Upload log file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-log
        path: test-log.txt
